--- 
title: "Курс статистики для биохимиков"
author: "АЕП"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
# github-repo: rstudio/bookdown-demo
description: "Черновая версия учебника."
editor_options: 
  chunk_output_type: console
---

# Что я хочу видеть в данной книге?

Структура книги

+ установка R: R/RStudio/Rtools/пакеты
+ преимущества R
+ базовый синтаксис
+ главы статистики с кодом для расчетов/примеров
  + типы данных (непрерывные, дискретные) и соответствующие типы в R
  + импорт данных, фильтрация, манипуляции
  + постановка эксперимента (рандомизация и дизайн в R)
  + summary, гистограммы, scatterplots, boxplots, pairs
  + сравнение групп
    + анализ распределения, типы предпосылок
    + доверительный интервал: нормальный, t и bootstrap; концепция интервала
    + связь доверительного интервала и p-value, уровень значимости и типы ошибок, вероятность найти эффект и не найти, мощность
    + тест перестановок
      + нулевая гипотеза
      + эмпирический p-value
      
+ справочник по основным операциям в R
  + переменные
  + типы данных и где что лучше использовать
  + импорт данных, ошибки, пропуски
  + операции
  + пайплайны
  + симуляции
  + чистые данные и манипуляции с ними
  + типы графиков: R-base, ggplot+cowplot/plotly, ggpubr
